### ISSUE TITLE
File "bpf_load.h" is not present in Ch2. listings

### ISSUE THREAD

**Issue by infominer75** [bpftools/linux-observability-with-bpf#12]
The source code from the book mention the presence of `bpf_load.h` which contains the helper boiler plate to compile and load the bpf program. This file is not currently present in the source repository for Ch 2.

Please check-in the file or provide correct updated instructions on how it can be found or elaborate on how the functionality present in that file can be implemented within another re-usable file.

My dev workstation is running the following:
`DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"`

Kernel version : `4.15.0-62-generic`
One more point for clarification - would the libbpf explicitly need to be synced/forked from this location?  https://github.com/libbpf/libbpf

**Comment by falcondb** [comment]
bpf_load.h is at /kernel-src/samples/bpf, add it to the header search path by -I, see if it works

**Comment by infominer75** [comment]
@falcondb Thank you for the pointer. I resolved the issues by using the same Makefile that is presented within the source code with modifications to suite Ubuntu 18.04 systems. An important aspect was that I had to installed `gcc-multilib` to ensure that compilation process for the loader completes. Without the multi-lib liibrariies I would not be able to find the `<bits/libc-header-start.h>`. Also, for the purposes of linking I had to build libbpf from source to make it available to the linker. As per my understanding this wont be required in Ubuntu 19.x since it comes with the Linux kernel version 5.0. An additional reference link that helped me is also being referenced here : https://blog.raymond.burkholder.net/index.php?/archives/1000-eBPF-Basics.html

**Comment by infominer75** [comment]
Will document my issues on a blog post in order to provide instructions on how to setup BPF programming on a Ubuntu 18.04 environment. Closing issue for now since the introduction example has started executing.

**Comment by fntlnz** [comment]
@infominer75 since you opened this there have been lots of improvements in the source code for [chapter 2](https://github.com/bpftools/linux-observability-with-bpf/tree/master/code/chapter-2/hello_world#chapter-2-hello-world) - it does not contain the same code as the book (we are updating the PDF copies and newer printed copies) but you can still follow here.
