### ISSUE TITLE
vagrant vm cannot compile hello world program because of missing bfd.h

### ISSUE THREAD

**Issue by yeya24** [bpftools/linux-observability-with-bpf#20]
Hello! I followed the guide to set up a vagrant fedora VM. And then I downloaded the kernel source into /kernel-src and tried to compile it, but it failed. It said `bfd.h: No such file or directory`, how to fix this? What other dependencies should I install?

``` Bash
[vagrant@bpfbook bpf]$ sudo make && sudo make install prefix=/

Auto-detecting system features:
...                        libbfd: [ OFF ]
...        disassembler-four-args: [ OFF ]

  CC       bpf_jit_disasm.o
/kernel-src/tools/bpf/bpf_jit_disasm.c:23:10: fatal error: bfd.h: No such file or directory
   23 | #include <bfd.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:57: bpf_jit_disasm.o] Error 1
```

**Comment by fntlnz** [comment]
Hi thanks for finding time to open the issue and making the content here better!

Can you check that the provisioning runs correctly?

The Vagrant VM is made to have all the needed dependencies you need to follow the examples, you can find them [here](https://github.com/bpftools/linux-observability-with-bpf/blob/master/Vagrantfile#L7)


To re-run the provisoning do:

```bash
vagrant up --provision
```

It should install the packages and exit without errors, if in doubt, please post the output here.

**Comment by yeya24** [comment]
@fntlnz  Thanks, it works after I re-create the VM

**Comment by fntlnz** [comment]
Thanks if you find anything else feel free to open an issue again :) @yeya24
