### ISSUE TITLE
Fedora 30, 31 Compile Errors

### ISSUE THREAD

**Issue by jnach** [bpftools/linux-observability-with-bpf#25]
Tested against F30 and F31. F31 was a brand new install.

`uname -r`
5.4.17-200.fc31.x86_64

`rpm -qa bcc`
bcc-0.12.0-1.fc31.x86_64

`rpm -qa clang`
clang-9.0.0-1.fc31.x86_64

1. All steps followed for downloading, making, and moving `/kernel-src`, and making BPF library
2. Git cloned into home directory,
3. `cd /home/$USER/linux-observability-with-bpf/code/chapter-2/hello_world`
4. `make bpfload`
Result:

clang -O2 -target bpf -c bpf_program.c -I/kernel-src/tools/testing/selftests/bpf -o bpf_program.o
clang -o monitor-exec -lelf -I/kernel-src/samples/bpf -I/kernel-src/tools/lib -I/kernel-src/tools/perf -I/kernel-src/tools/include -L/usr/local/lib64 -lbpf \
        /kernel-src/samples/bpf/bpf_load.c loader.c
/usr/bin/ld: /tmp/bpf_load-67fc3d.o: in function `sys_perf_event_open':
bpf_load.c:(.text+0x1fde): undefined reference to `test_attr__enabled'
/usr/bin/ld: bpf_load.c:(.text+0x2015): undefined reference to `test_attr__open'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:28: bpfload] Error 1

An initial web search shows some activity in 2014 around the perf.h header, though it doesn't seem to be resolved in the Fedora tree.

**Comment by fntlnz** [comment]
Thanks for reporting @jnach - I'll try to repro this

**Comment by wybczu** [comment]
I had the same issue on Linux 5.5. Fixed it by adding `-DHAVE_ATTR_TEST=0` to compiler flags.

Below are the links to related kernel commits.

-  https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=06f84d1989b7e58d56fa2e448664585749d41221
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=fce9501aec6bdda45ef3a5e365a5e0de7de7fe2d

**Comment by fntlnz** [comment]
@jnach - does the fix proposed by @wybczu works for you?

I still need to try this :angel:

**Comment by jnach** [comment]
As do I, pardon the delay given current events.

**Comment by jnach** [comment]
@fntlnz I'm not afraid of recompiling the kernel with different options, but it doesn't lend itself well to claiming support for the Fedora tree

**Comment by jnach** [comment]
It might make sense to include guidance on kernel options and versioning in addition to distribution to keep readers on track, given these options are otherwise breaking changes

**Comment by saireddyavs** [comment]
i have added ```-DHAVE_ATTR_TEST=0``` and the compilation was done without  error
but when i executed it using ```./monitor-exec``` it's showing 
```
bpf_load_program() err=1
The kernel didn't load the BPF program

```
What is the reason for it? and how to solve it? why it's not loading?

**Comment by benja-wu** [comment]
> i have added `-DHAVE_ATTR_TEST=0` and the compilation was done without error
> but when i executed it using `./monitor-exec` it's showing
> 
> ```
> bpf_load_program() err=1
> The kernel didn't load the BPF program
> ```
> 
> What is the reason for it? and how to solve it? why it's not loading?

I had met this problem too. 
* Firstly, I used `strace` to see what's going on, then I found it failed in 
```
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_TRACEPOINT, insn_cnt=14, insns=0xa560e0, license="GPL", log_level=0, log_size=0, log_buf=NULL, kern_version=KERNEL_VERSION(0, 0, 0), prog_flags=0, prog_name="", prog_ifindex=0, expected_attach_type=BPF_CGROUP_INET_INGRESS}, 112) = -1 EPERM (Operation not permitted)
```
Since I was running this program in a docker container environment and already in `root` privilege, I added `docker run --privileged ...`. Problem solved! But a new error popped up `failed to open event syscalls/sys_enter_execve`.
* Again, I used `strace` to follow `moniter-exec`, and found that a directory was missing in the docker container. 
It was `/sys/kernel/debug/tracing/` directory.
 So I used ` mount -t debugfs none /sys/kernel/debug`. Finally, it worked! 
```
 ./monitor-exec 
           <...>-91340 [002] ....  8782.662546: 0: Hello, BPF World!
           <...>-91348 [001] ....  8782.672381: 0: Hello, BPF World!
           <...>-91349 [002] ....  8782.971433: 0: Hello, BPF World!
           <...>-91356 [000] ....  8782.982302: 0: Hello, BPF World!
           <...>-91357 [003] ....  8782.984960: 0: Hello, BPF World!
           <...>-91364 [001] ....  8782.993525: 0: Hello, BPF World!
           <...>-91365 [003] ....  8782.995541: 0: Hello, BPF World!
           <...>-91372 [001] ....  8783.003363: 0: Hello, BPF World!
           <...>-91373 [002] ....  8785.120058: 0: Hello, BPF World!

```
So hope the descriptions above can help you with this problem.  @saireddyavs

**Comment by ch33hau** [comment]
Hi there, I have submitted a PR, by changing the command to: 
```bash
sudo ./monitor-exec
``` 

Though the instruction mentioned that the command should be executed with the root privileges, a quick copy and paste from the example will cause this error. ( at least that was my case 😅 )
