### ISSUE TITLE
Chapter 2 "Hello World" Not compiling

### ISSUE THREAD

**Issue by rtkaratekid** [bpftools/linux-observability-with-bpf#26]
Spun up a Vagrant instance today with the provided Vagrantfile. Immediately cloned the repo and ran make and had an error. I'm not a Makefile whiz so maybe someone here could find the issue faster than myself.

```sh
[vagrant@bpfbook ~]$ git clone https://github.com/bpftools/linux-observability-with-bpf.git ~/linux-observability-with-bpf
Cloning into '/home/vagrant/linux-observability-with-bpf'...
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 284 (delta 18), reused 27 (delta 9), pack-reused 226
Receiving objects: 100% (284/284), 183.59 KiB | 657.00 KiB/s, done.
Resolving deltas: 100% (97/97), done.

[vagrant@bpfbook ~]$ cd ~/linux-observability-with-bpf/code/chapter-2/hello_world

[vagrant@bpfbook hello_world]$ make bpfload
make: *** No rule to make target '/kernel-src/samples/bpf/bpf_load.c', needed by 'build'.  Stop.
```

I tried building manually, but I have to figure out where the bpf_load.h file is first and link it to the compilation.

The book is fantastic though and I'm really excited to learn more about BPF programming. I'll be working through all the examples so I can verify whether or not they're all working if that's helpful at all?

**Comment by terryvogelsang** [comment]
Hi there,

It might be due to `/kernel-src/samples/bpf_load.c` file missing.

Did you follow the instructions completely : https://github.com/bpftools/linux-observability-with-bpf#install-vagrant ?

Please make sure you did not miss this part :

>Before going on, make sure you download the kernel source tree in this repository. It is needed as a dependency for some examples.
We will be downloading the code for Kernel 5.0.9 - We are avoiding a git clone here because the Git history of the kernel is very big.
>
> In the machine:
>
>```bash
>cd /tmp
>wget -c https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.0.9.tar.gz -O - | tar -xz
>sudo mv linux-5.0.9 /kernel-src
>```
>
>At this point, we need to compile the `libbpf` library:
>
>```
>cd /kernel-src/tools/lib/bpf
>make && sudo make install prefix=/
>```

Hope this will help 🙂

**Comment by rtkaratekid** [comment]
I figured out what my dumb mistake was, thanks for being patient. I was reading the Readme too fast and didn't notice that the instruction details were collapsed in each of the sections. Went back to the raw markdown and saw what I had missed.

I'm definitely an the idiot here... but if more people have this issue maybe the line "Please expand the details of the environment you want to work on." should be bolded or something? It's really nitpicky though, so I'd just consider my mistake as a silly one-off.

Thanks for the quick reply!
