### ISSUE TITLE
Is this all the code?

### ISSUE THREAD

**Issue by sergeyfd** [bpftools/linux-observability-with-bpf#3]
Hello.

Per book text there should be examples starting from Chapter 1, including code for bpf_load.c and bpf_load.h. All of this seems missing.

**Comment by fntlnz** [comment]
Hi @sergeyfd , no it is not - we miss the code from the first chapters from David (@calavera) .

**Comment by fntlnz** [comment]
I added the code for the remaining chapters, I'll follow up with instructions on how to setup the environment.

**Comment by sergeyfd** [comment]
Thanks!

**Comment by fntlnz** [comment]
There's progress on the Vagrant environment here https://github.com/bpftools/linux-observability-with-bpf/pull/6
