### ISSUE TITLE
Couldn't pass the parameters of system call to kprobe in ebpf program

### ISSUE THREAD

**Issue by tvsanthoshkumar** [bpftools/linux-observability-with-bpf#36]
Hi,

Thanks for writing such a nice book to help us in understanding the ebpf fundamentals.

I am new to eBPF world. I am running ubuntu18.04 with kernel version 5.3.0-42-generic.

I want to observe the parameters passed to system call (sendto/recvmsg). Can you please let me know the way to get the values passed to these params?

I took the program explained in chapter-4 under kprobe section. But it is throwing following error.

/virtual/main.c:2:18: error: 'void' must be the first and only parameter if specified
int do_sys_execve(struct pt_regs *ctx, void filename, void argv, void envp) {   
                 ^
/virtual/main.c:2:18: error: 'void' must be the first and only parameter if specified
/virtual/main.c:2:18: error: 'void' must be the first and only parameter if specified
3 errors generated.
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    bpf = BPF(text = bpf_source)	
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 343, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>

**Comment by tvsanthoshkumar** [comment]
Verified bcc code to get some sample example. It worked. Thanks

**Comment by tvsanthoshkumar** [comment]
The code was executing and compiling successfully. But I am getting random or null values as parameters.

**Comment by fntlnz** [comment]
@tvsanthoshkumar can you post a screenshot or your output?

**Comment by tvsanthoshkumar** [comment]
The screenshot of the program is as follows.

![Screenshot from 2020-04-04 23-51-02](https://user-images.githubusercontent.com/3885342/78458514-9f3b6880-76cf-11ea-9162-669ffe09a4ca.png)

As mentioned, I was using this program as a reference to figure out the parameters passed to sendto system call. But it is printing random garbage values. I don't know whats the issue with my program.

Program to find the parameters of sendto using kprobe is:

#include <uapi/linux/ptrace.h>
#include <linux/sched.h>

struct function_call {
  u64 pid;
  char fun_name;
};

BPF_HASH(cache, struct function_call, u64);

int sendto_trace_start_time(struct pt_regs *ctx, int sockfd, const void *buf, size_t len, int flags, const struct sockaddr *dest_addr, u64 addrlen) {
  struct function_call key={};
  key.pid = bpf_get_current_pid_tgid();
  key.fun_name = 's';
  u64 start_time_ns = bpf_ktime_get_ns();
  cache.update(&key, &start_time_ns);
 /* bpf_trace_printk("length is: %d \\n", len);*/
  return 0;
}
