### ISSUE TITLE
Chapter2 undefined reference to `read_trace_pipe'

### ISSUE THREAD

**Issue by Juntaran** [bpftools/linux-observability-with-bpf#50]
`
load_bpf_file.c:11:5: warning: implicit declaration of function 'read_trace_pipe' is invalid in C99 [-Wimplicit-function-declaration]
    read_trace_pipe();
    ^
1 warning generated.
/tmp/bpf_load-e24bf7.o: In function `sys_perf_event_open':
bpf_load.c:(.text+0x1f5e): undefined reference to `test_attr__enabled'
bpf_load.c:(.text+0x1f95): undefined reference to `test_attr__open'
/tmp/load_bpf_file-e4f8ca.o: In function `main':
load_bpf_file.c:(.text+0x4e): undefined reference to `read_trace_pipe'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:28: bpfload] Error 1
`

CentOS 8
kernel: 5.9.3-1.el8.elrepo.x86_64

**Comment by beihai0xff** [comment]
I use CentOS8 and 5.9.x linux kernel, too. And I have the same problem with you.

I saw the source code in `/kernel-src/samples/bpf/bpf_load.c`, but I didn't find the function `read_trace_pipe`. Then I found a commit [samples, bpf: Move read_trace_pipe to trace_helpers](https://beargit.pw/mirror/linux/-/commit/24a6034acc922f1f6292636be4ec4dc3d9b4d2d7), from **kernel-5.7** the function `read_trace_pipe` has been moved to file `/kernel-src/tools/testing/selftests/bpf/trace_helpers.c`.

To solve this problem:

1. add a header `#include "trace_helpers.h"` in loader.c;
2. add `BPFTEST = /kernel-src/tools/testing/selftests/bpf/trace_helpers.c` in Makefile;
3. then modify Makefile target `bpfload` into:
```
bpfload: build
	clang $(CFLAGS) -o $(EXECABLE) -lelf $(LOADINCLUDE) $(LIBRARY_PATH) $(BPFSO) \
        $(BPFLOADER) $(BPFTEST) loader.c
```
This solution works in my machine, here's the complete file.
**loader.c:**
```
#include "bpf_load.h"
#include "trace_helpers.h"
#include <stdio.h>

int main(int argc, char **argv) {
  if (load_bpf_file("bpf_program.o") != 0) {
    printf("The kernel didn't load the BPF program\n");
    return -1;
  }

  read_trace_pipe();

  return 0;
}
```
**Makefile:**
```
CLANG = clang

EXECABLE = monitor-exec

BPFCODE = bpf_program

BPFTOOLS = /kernel-src/samples/bpf
BPFLOADER = $(BPFTOOLS)/bpf_load.c

BPFTEST = /kernel-src/tools/testing/selftests/bpf/trace_helpers.c

CCINCLUDE += -I/kernel-src/tools/testing/selftests/bpf

LOADINCLUDE += -I/kernel-src/samples/bpf
LOADINCLUDE += -I/kernel-src/tools/lib
LOADINCLUDE += -I/kernel-src/tools/perf
LOADINCLUDE += -I/kernel-src/tools/include
LOADINCLUDE += -I/kernel-src/tools/testing/selftests/bpf
LIBRARY_PATH = -L/usr/local/lib64
BPFSO = -lbpf

CFLAGS += $(shell grep -q "define HAVE_ATTR_TEST 1" /kernel-src/tools/perf/perf-sys.h \
                  && echo "-DHAVE_ATTR_TEST=0")

.PHONY: clean $(CLANG) bpfload build

clean:
	rm -f *.o *.so $(EXECABLE)

build: ${BPFCODE.c} ${BPFLOADER}
	$(CLANG) -O2 -target bpf -c $(BPFCODE:=.c) $(CCINCLUDE) -o ${BPFCODE:=.o}

bpfload: build
	clang $(CFLAGS) -o $(EXECABLE) -lelf $(LOADINCLUDE) $(LIBRARY_PATH) $(BPFSO) \
        $(BPFLOADER) $(BPFTEST) loader.c

$(EXECABLE): bpfload

.DEFAULT_GOAL := $(EXECABLE)

```
**Forgive my poor English** 😥

**Comment by zhangbo1882** [comment]
#include "bpf_load.h"
#include <stdio.h>
#include <fcntl.h>
#include <stdlib.h>
#include <unistd.h>
#define DEBUGFS "/sys/kernel/debug/tracing/"

void read_trace_pipe(void)
{
        int trace_fd;

        trace_fd = open(DEBUGFS "trace_pipe", O_RDONLY, 0);
        if (trace_fd < 0)
                return;

        while (1) {
                static char buf[4096];
                ssize_t sz;

                sz = read(trace_fd, buf, sizeof(buf) - 1);
                if (sz > 0) {
                        buf[sz] = 0;
                        puts(buf);
                }
        }
}

int main(int argc, char **argv) {
  if (load_bpf_file("bpf_program.o") != 0) {
    printf("The kernel didn't load the BPF program\n");
    return -1;
  }

  read_trace_pipe();

  return 0;
}

**Comment by zhangbo1882** [comment]
You can add the function definition by yourself. I have met your the same issue.

**Comment by Dantali0n** [comment]
This breaks in kernel 5.10 as both bpf_load.h and trace_helpers.h define `bpf_set_link_xdp_fd(int ifindex, int fd, __u32 flags)`.

**Comment by liupzmin** [comment]
> I use CentOS8 and 5.9.x linux kernel, too. And I have the same problem with you.
> 
> I saw the source code in `/kernel-src/samples/bpf/bpf_load.c`, but I didn't find the function `read_trace_pipe`. Then I found a commit [samples, bpf: Move read_trace_pipe to trace_helpers](https://beargit.pw/mirror/linux/-/commit/24a6034acc922f1f6292636be4ec4dc3d9b4d2d7), from **kernel-5.7** the function `read_trace_pipe` has been moved to file `/kernel-src/tools/testing/selftests/bpf/trace_helpers.c`.
> 
> To solve this problem:
> 
> 1. add a header `#include "trace_helpers.h"` in loader.c;
> 2. add `BPFTEST = /kernel-src/tools/testing/selftests/bpf/trace_helpers.c` in Makefile;
> 3. then modify Makefile target `bpfload` into:
> 
> ```
> bpfload: build
> 	clang $(CFLAGS) -o $(EXECABLE) -lelf $(LOADINCLUDE) $(LIBRARY_PATH) $(BPFSO) \
>         $(BPFLOADER) $(BPFTEST) loader.c
> ```
> 
> This solution works in my machine, here's the complete file. **loader.c:**
> 
> ```
> #include "bpf_load.h"
> #include "trace_helpers.h"
> #include <stdio.h>
> 
> int main(int argc, char **argv) {
>   if (load_bpf_file("bpf_program.o") != 0) {
>     printf("The kernel didn't load the BPF program\n");
>     return -1;
>   }
> 
>   read_trace_pipe();
> 
>   return 0;
> }
> ```
> 
> **Makefile:**
> 
> ```
> CLANG = clang
> 
> EXECABLE = monitor-exec
> 
> BPFCODE = bpf_program
> 
> BPFTOOLS = /kernel-src/samples/bpf
> BPFLOADER = $(BPFTOOLS)/bpf_load.c
> 
> BPFTEST = /kernel-src/tools/testing/selftests/bpf/trace_helpers.c
> 
> CCINCLUDE += -I/kernel-src/tools/testing/selftests/bpf
> 
> LOADINCLUDE += -I/kernel-src/samples/bpf
> LOADINCLUDE += -I/kernel-src/tools/lib
> LOADINCLUDE += -I/kernel-src/tools/perf
> LOADINCLUDE += -I/kernel-src/tools/include
> LOADINCLUDE += -I/kernel-src/tools/testing/selftests/bpf
> LIBRARY_PATH = -L/usr/local/lib64
> BPFSO = -lbpf
> 
> CFLAGS += $(shell grep -q "define HAVE_ATTR_TEST 1" /kernel-src/tools/perf/perf-sys.h \
>                   && echo "-DHAVE_ATTR_TEST=0")
> 
> .PHONY: clean $(CLANG) bpfload build
> 
> clean:
> 	rm -f *.o *.so $(EXECABLE)
> 
> build: ${BPFCODE.c} ${BPFLOADER}
> 	$(CLANG) -O2 -target bpf -c $(BPFCODE:=.c) $(CCINCLUDE) -o ${BPFCODE:=.o}
> 
> bpfload: build
> 	clang $(CFLAGS) -o $(EXECABLE) -lelf $(LOADINCLUDE) $(LIBRARY_PATH) $(BPFSO) \
>         $(BPFLOADER) $(BPFTEST) loader.c
> 
> $(EXECABLE): bpfload
> 
> .DEFAULT_GOAL := $(EXECABLE)
> ```
> 
> **Forgive my poor English** disappointed_relieved

hi, I did what you said, and compiled. but I got another error when  executing

```
bpf_load_program() err=1
The kernel didn't load the BPF program
```

**Forgive my poor English too**

**Comment by beihai0xff** [comment]
> > I use CentOS8 and 5.9.x linux kernel, too. And I have the same problem with you.
> > I saw the source code in `/kernel-src/samples/bpf/bpf_load.c`, but I didn't find the function `read_trace_pipe`. Then I found a commit [samples, bpf: Move read_trace_pipe to trace_helpers](https://beargit.pw/mirror/linux/-/commit/24a6034acc922f1f6292636be4ec4dc3d9b4d2d7), from **kernel-5.7** the function `read_trace_pipe` has been moved to file `/kernel-src/tools/testing/selftests/bpf/trace_helpers.c`.
> > To solve this problem:
> > 
> > 1. add a header `#include "trace_helpers.h"` in loader.c;
> > 2. add `BPFTEST = /kernel-src/tools/testing/selftests/bpf/trace_helpers.c` in Makefile;
> > 3. then modify Makefile target `bpfload` into:
> > 
> > ```
> > bpfload: build
> > 	clang $(CFLAGS) -o $(EXECABLE) -lelf $(LOADINCLUDE) $(LIBRARY_PATH) $(BPFSO) \
> >         $(BPFLOADER) $(BPFTEST) loader.c
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This solution works in my machine, here's the complete file. **loader.c:**
> > ```
> > #include "bpf_load.h"
> > #include "trace_helpers.h"
> > #include <stdio.h>
> > 
> > int main(int argc, char **argv) {
> >   if (load_bpf_file("bpf_program.o") != 0) {
> >     printf("The kernel didn't load the BPF program\n");
> >     return -1;
> >   }
> > 
> >   read_trace_pipe();
> > 
> >   return 0;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Makefile:**
> > ```
> > CLANG = clang
> > 
> > EXECABLE = monitor-exec
> > 
> > BPFCODE = bpf_program
> > 
> > BPFTOOLS = /kernel-src/samples/bpf
> > BPFLOADER = $(BPFTOOLS)/bpf_load.c
> > 
> > BPFTEST = /kernel-src/tools/testing/selftests/bpf/trace_helpers.c
> > 
> > CCINCLUDE += -I/kernel-src/tools/testing/selftests/bpf
> > 
> > LOADINCLUDE += -I/kernel-src/samples/bpf
> > LOADINCLUDE += -I/kernel-src/tools/lib
> > LOADINCLUDE += -I/kernel-src/tools/perf
> > LOADINCLUDE += -I/kernel-src/tools/include
> > LOADINCLUDE += -I/kernel-src/tools/testing/selftests/bpf
> > LIBRARY_PATH = -L/usr/local/lib64
> > BPFSO = -lbpf
> > 
> > CFLAGS += $(shell grep -q "define HAVE_ATTR_TEST 1" /kernel-src/tools/perf/perf-sys.h \
> >                   && echo "-DHAVE_ATTR_TEST=0")
> > 
> > .PHONY: clean $(CLANG) bpfload build
> > 
> > clean:
> > 	rm -f *.o *.so $(EXECABLE)
> > 
> > build: ${BPFCODE.c} ${BPFLOADER}
> > 	$(CLANG) -O2 -target bpf -c $(BPFCODE:=.c) $(CCINCLUDE) -o ${BPFCODE:=.o}
> > 
> > bpfload: build
> > 	clang $(CFLAGS) -o $(EXECABLE) -lelf $(LOADINCLUDE) $(LIBRARY_PATH) $(BPFSO) \
> >         $(BPFLOADER) $(BPFTEST) loader.c
> > 
> > $(EXECABLE): bpfload
> > 
> > .DEFAULT_GOAL := $(EXECABLE)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Forgive my poor English** disappointed_relieved
> 
> hi, I did what you said, and compiled. but I got another error when executing
> 
> ```
> bpf_load_program() err=1
> The kernel didn't load the BPF program
> ```
> 
> **Forgive my poor English too**

see this issue? https://github.com/bpftools/linux-observability-with-bpf/issues/25
