### ISSUE TITLE
Chapter 7 bcc example on Ubuntu: warning 'KBUILD_MODNAME' macro redefined

### ISSUE THREAD

**Issue by dlanders911** [bpftools/linux-observability-with-bpf#56]
After modifying the loader.py file for my device and invoking python3, this warning is displayed. Is this a problem with my setup? Is it something I can "fix"?

```
root@xxxxxx:~/eBPF/linux-observability-with-bpf/code/chapter-7/bcc# python3 loader.py
/virtual/main.c:1:9: warning: 'KBUILD_MODNAME' macro redefined [-Wmacro-redefined]
#define KBUILD_MODNAME "program"
        ^
<command line>:6:9: note: previous definition is here
#define KBUILD_MODNAME "bcc"
        ^
1 warning generated.
Printing packet counts per IP protocol-number, hit CTRL+C to stop
1: 1 pkt/s
1: 1 pkt/s
1: 1 pkt/s
1: 1 pkt/s
1: 1 pkt/s
1: 1 pkt/s
166: 2 pkt/s
1: 1 pkt/s
166: 0 pkt/s
1: 1 pkt/s
166: 0 pkt/s
1: 1 pkt/s
166: 0 pkt/s
1: 0 pkt/s
166: 0 pkt/s
1: 0 pkt/s
166: 0 pkt/s
^CRemoving filter from device

```
System is:
- Ubuntu 18.04 LTS
- 5.3.0-26-generic kernel
- Python 3.6.9
- Following bcc-related pkgs installed:
  - bcc-tools/stable,now 0.10.0-1 all [installed]
  - libbcc/stable,now 0.10.0-1 all [installed,automatic]
  - libbcc-examples/stable,now 0.10.0-1 amd64 [installed]
  - libcc1-0/bionic-updates,now 8.4.0-1ubuntu1~18.04 amd64 [installed,automatic]
  - python-bcc/stable,now 0.10.0-1 all [installed,automatic]
  - python3-bcc/stable,now 0.10.0-1 all [installed]

However, I also built bcc from sources per [bcc's INSTALL.md](https://github.com/iovisor/bcc/blob/master/INSTALL.md#install-and-compile-bcc)

And, just FYI, there are two references to 'trough' instead of 'through' in the README.md file for this example.

**Comment by dlanders911** [comment]
Commenting out the first line of the file program.c fixed this warning:
//#define KBUILD_MODNAME "program"

**Comment by fntlnz** [comment]
Yeah I noticed this in many programs I maintain too!
Will leave this open for others to discover, we probably want to add a comment on that one and not just remove it because for older kernels it's needed.
