### ISSUE TITLE
Chapter-4/usdt: TypeError: __init__() got an unexpected keyword argument 'usdt'

### ISSUE THREAD

**Issue by ZiyangYuFCB** [bpftools/linux-observability-with-bpf#59]
When I runing the example code example.py in code/chapter-4/usdt, there is a error as "TypeError: __init__() got an unexpected keyword argument 'usdt'", I can't solve it after searching google. Can anyone help me?

**Comment by wangjinnana** [comment]
maybe this link will help you: https://stackoverflow.com/questions/62641551/getting-bpf-programs-working-with-usdt-probes-dtrace-in-linux

**Comment by ZiyangYuFCB** [comment]
> maybe this link will help you: https://stackoverflow.com/questions/62641551/getting-bpf-programs-working-with-usdt-probes-dtrace-in-linux

yeah, thanks a lot. I've debugged as the link says. However, the program still shows the exception:
`File "./usdt.py", line 16, in <module>`
`    bpf = BPF(text = bpf_source, usdt_contexts = [usdt])`
`  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 350, in __init__`
   ` usdt_context.attach_uprobes(self)`
`  File "/usr/lib/python3/dist-packages/bcc/usdt.py", line 193, in attach_uprobes`
  `  bpf.attach_uprobe(name=binpath.decode(), fn_name=fn_name.decode(),`
`  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1026, in attach_uprobe`
`    fn = self.load_func(fn_name, BPF.KPROBE)`
 ` File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 394, in load_func`
 `   raise Exception("Failed to load BPF program %s: %s" %`
`Exception: Failed to load BPF program b'trace_binary_exec': Invalid argument`

(I have already installed the bpfcc-tools and linux-header)

**Comment by wangjinnana** [comment]
do you have libbcc.so in your system

**Comment by ZiyangYuFCB** [comment]
yes, there is libbcc.so in my system. Thanks a lot. I have solved it with this link&nbsp;https://blog.csdn.net/longyu_wlz/article/details/109902171




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bpftools/linux-observability-with-bpf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 中午11:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bpftools/linux-observability-with-bpf] Chapter-4/usdt: TypeError: __init__() got an unexpected keyword argument 'usdt' (#59)





 
do you have libbcc.so in your system

**Comment by ZiyangYuFCB** [comment]
> > maybe this link will help you: https://stackoverflow.com/questions/62641551/getting-bpf-programs-working-with-usdt-probes-dtrace-in-linux
> 
> yeah, thanks a lot. I've debugged as the link says. However, the program still shows the exception:
> `File "./usdt.py", line 16, in <module>`
> ` bpf = BPF(text = bpf_source, usdt_contexts = [usdt])`
> ` File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 350, in __init__`
> ` usdt_context.attach_uprobes(self)`
> ` File "/usr/lib/python3/dist-packages/bcc/usdt.py", line 193, in attach_uprobes`
> ` bpf.attach_uprobe(name=binpath.decode(), fn_name=fn_name.decode(),`
> ` File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1026, in attach_uprobe`
> ` fn = self.load_func(fn_name, BPF.KPROBE)`
> ` File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 394, in load_func`
> ` raise Exception("Failed to load BPF program %s: %s" %`
> `Exception: Failed to load BPF program b'trace_binary_exec': Invalid argument`
> 
> (I have already installed the bpfcc-tools and linux-header)

solved with this [https://blog.csdn.net/longyu_wlz/article/details/109902171](url)

**Comment by wangjinnana** [comment]
what's wrong with you

**Comment by ZiyangYuFCB** [comment]
no idea. I just reinstalled the python3-bcc, bpfcc-tools then it runs&nbsp;



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 11, 2021 11:33 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [bpftools/linux-observability-with-bpf] Chapter-4/usdt: TypeError: __init__() got an unexpected keyword argument 'usdt' (#59)




 
what's wrong with you

**Comment by fntlnz** [comment]
This was solved by #64 - closing
