### ISSUE TITLE
Chapter 3 how to compile 

### ISSUE THREAD

**Issue by milind69** [bpftools/linux-observability-with-bpf#63]
Is there instruction on how to compile map_create.c ?
 I tried copying Makefile from hello_world , initially it failed on "bpf_load.h not found" error 

 I then  modified it to include additional lib it compiled but failed on running 

below is the make output 

make 
clang -O2 -target bpf -c map_create.c  -I/kernel-src/tools/testing/selftests/bpf -I/kernel-src/tools/lib/bpf -I/kernel-src/samples/bpf -I/kernel-src/tools/lib -o map_create.o
clang  -o map_manage -lelf -I/kernel-src/samples/bpf -I/kernel-src/tools/lib -I/kernel-src/tools/perf -I/kernel-src/tools/include -L/usr/local/lib64 -lbpf \
        /kernel-src/samples/bpf/bpf_load.c loader.c

[root@Milindrh8 maps]# ls
loader.c  Makefile  map_create.c  map_create.o  map_manage

[root@Milindrh8 maps]# ./map_manage 
invalid relo for insn[6].code 0x85                          <<< error 
The kernel didn't load the BPF program

My OS details 
 uname -a
Linux Milindrh8 4.18.0-305.3.1.el8_4.x86_64 #1 SMP Mon May 17 10:08:25 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

hello-world compiles and run ok on same system

**Comment by dddddai** [comment]
1.There is no file named `map_create.c`, do you mean `map_pinning_save.c` ？

2.There is no need to use `loader.c`. Here is my Makefile.
```
CLANG = clang

EXECABLE = map_write

BPFTOOLS = /kernel-src/samples/bpf
BPFLOADER = $(BPFTOOLS)/bpf_load.c

CCINCLUDE += -I/kernel-src/tools/testing/selftests/bpf

LOADINCLUDE += -I/kernel-src/samples/bpf
LOADINCLUDE += -I/kernel-src/tools/lib
LOADINCLUDE += -I/kernel-src/tools/perf
LOADINCLUDE += -I/kernel-src/tools/include
LIBRARY_PATH = -L/usr/local/lib64
BPFSO = -lbpf

.PHONY: clean build

clean:
	rm -f *.o *.so $(EXECABLE)

build:
	clang -o $(EXECABLE) -lelf $(LOADINCLUDE) $(LIBRARY_PATH) $(BPFSO) \
        $(BPFLOADER) map_pinning_save.c
```

Run `make build` to compile it, and compile `map_pinning_fetch.c` in the same way.

**Comment by milind69** [comment]
I get the error below
ase) milind@milind-HP-ubuntu:~/linux-observability-with-bpf/code/chapter-3/bpf_fs$ make build
clang -o map-pin -lelf -I/kernel-src/samples/bpf -I/kernel-src/tools/lib -I/kernel-src/tools/perf -I/kernel-src/tools/include -L/usr/local/lib64 -lbpf \
        /kernel-src/samples/bpf/bpf_load.c map_pinning_save.c
map_pinning_save.c:7:10: fatal error: 'bpf_util.h' file not found
#include "bpf_util.h"
         ^~~~~~~~~~~~
1 error generated.
make: *** [Makefile:31: build] Error 1

**Comment by dddddai** [comment]
Yes I got the same error, and I just remove `#include "bpf_util.h"`, then it would be compiled successfully.

**Comment by fntlnz** [comment]
If y'all find a solution that can be shared with a PR feel free to open one or let me know how to improve. Thank you for opening this @milind69 and for answering @dddddai
