### ISSUE TITLE
Make sure all the examples work in the Vagrant environment and have a description

### ISSUE THREAD

**Issue by fntlnz** [bpftools/linux-observability-with-bpf#7]
Work continuation from #6 

Items with a tick have already been tested in the Vagrant environment and have a detailed description in this repo and in the book.

  - [x] [Hello World](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-2/hello_world)
  - [ ] [Kprobes](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-4/kprobes)
  - [ ] [Kretprobes](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-4/kretprobes)
  - [ ] [Uprobes](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-4/uprobes)
  - [ ] [Uretprobes ](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-4/uretprobes)
  - [ ]  [Tracepoints](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-4/tracepoints)
  - [ ] [User Statically Defined Tracepoints](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-4/usdt)
  - [ ] [Flame Graphs](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-4/flamegraphs)
  - [ ] [Histograms](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-4/histograms)
  - [ ] [Perf Events](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-4/histograms)
  - [x]  [Packet filtering for raw sockets](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-6/packet-filtering-raw-sockets)
  - [x] [Traffic control classifier program using cls_bpf](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-6/tc-flow-bpf-cls)
  - [x] [XDP using iproute2 as a loader](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-7/iproute2)
  - [x] [XDP using BCC as a loader](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-7/bcc)
  - [x] [Testing XDP programs](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-7/prog-test-run)
  - [x] [Seccomp BPF filter example](/bpftools/linux-observability-with-bpf/tree/master/code/chapter-8/seccomp)

**Comment by fntlnz** [comment]
If anyone wants to take some items here I'll be eternally grateful!

Thanks a lot for your help so far @falcondb @0xmilkmix @madorn ! :heart_decoration:

**Comment by 0xmilkmix** [comment]
> If anyone wants to take some items here I'll be eternally grateful!
> Thanks a lot for your help so far @falcondb @0xmilkmix @madorn ! 💟

We've the easy part after you wrote an entire book ;) Thank you!
