### ISSUE TITLE
【git fail】git clone --depth 1 git://kernel.ubuntu.com/ubuntu/ubuntu-bionic.git  

### ISSUE THREAD

**Issue by lishicheng2021** [bpftools/linux-observability-with-bpf#72]
git clone --depth 1 git://kernel.ubuntu.com/ubuntu/ubuntu-bionic.git

connection timed out

**Comment by fntlnz** [comment]
It should be available now, I just tested on my environment.


The web version is here https://kernel.ubuntu.com/git/ubuntu/ubuntu-bionic.git/
